### ISSUE TITLE
Task 3 - check hti out

### ISSUE THREAD

**Issue by amichai-bd** [kereng1/keren_howto#3]
- [x] set this
- [x] and this
- [x] and this
- [x] and this

**Comment by kereng1** [comment]
done, what now?

**Comment by amichai-bd** [comment]
Just few more:
- [ ] this
- [ ] this
- [ ] and this

**Comment by amichai-bd** [comment]
You may close this issue if all are marked as done

**Comment by kereng1** [comment]
all are marked , thank you
